CREATE TABLE MS_USER(
    USER_ID VARCHAR(100) NOT NULL,
    PASSWD VARCHAR(100) NOT NULL,
    USER_NM VARCHAR(100) NOT NULL,
    BIRTHDAY DATE NOT NULL,
    CREATE_DATE TIMESTAMP,
    UPDATE_DATE TIMESTAMP,
    PRIMARY KEY(USER_ID)
);