CREATE TABLE TR_POSTS(
    POST_ID BIGSERIAL PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL REFERENCES MS_USER(USER_ID),
    POST_TEXT VARCHAR(100),
    POST_DATE TIMESTAMP
);
CREATE UNIQUE INDEX IDX_TR_POSTS_1 ON TR_POSTS (POST_ID);
CREATE INDEX IDX_TR_POSTS_2 ON TR_POSTS (USER_ID);